# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/andrewjiang/Desktop/eecs440/search-engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/andrewjiang/Desktop/eecs440/search-engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/andrewjiang/Desktop/eecs440/search-engine/CMakeFiles /Users/andrewjiang/Desktop/eecs440/search-engine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/andrewjiang/Desktop/eecs440/search-engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named search_engine

# Build rule for target.
search_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 search_engine
.PHONY : search_engine

# fast build rule for target.
search_engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/build
.PHONY : search_engine/fast

index/ISR.o: index/ISR.cpp.o
.PHONY : index/ISR.o

# target to build an object file
index/ISR.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/index/ISR.cpp.o
.PHONY : index/ISR.cpp.o

index/ISR.i: index/ISR.cpp.i
.PHONY : index/ISR.i

# target to preprocess a source file
index/ISR.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/index/ISR.cpp.i
.PHONY : index/ISR.cpp.i

index/ISR.s: index/ISR.cpp.s
.PHONY : index/ISR.s

# target to generate assembly for a file
index/ISR.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/index/ISR.cpp.s
.PHONY : index/ISR.cpp.s

index/Ipost.o: index/Ipost.cpp.o
.PHONY : index/Ipost.o

# target to build an object file
index/Ipost.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/index/Ipost.cpp.o
.PHONY : index/Ipost.cpp.o

index/Ipost.i: index/Ipost.cpp.i
.PHONY : index/Ipost.i

# target to preprocess a source file
index/Ipost.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/index/Ipost.cpp.i
.PHONY : index/Ipost.cpp.i

index/Ipost.s: index/Ipost.cpp.s
.PHONY : index/Ipost.s

# target to generate assembly for a file
index/Ipost.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/index/Ipost.cpp.s
.PHONY : index/Ipost.cpp.s

index/Post.o: index/Post.cpp.o
.PHONY : index/Post.o

# target to build an object file
index/Post.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/index/Post.cpp.o
.PHONY : index/Post.cpp.o

index/Post.i: index/Post.cpp.i
.PHONY : index/Post.i

# target to preprocess a source file
index/Post.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/index/Post.cpp.i
.PHONY : index/Post.cpp.i

index/Post.s: index/Post.cpp.s
.PHONY : index/Post.s

# target to generate assembly for a file
index/Post.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/index/Post.cpp.s
.PHONY : index/Post.cpp.s

index/PostingList.o: index/PostingList.cpp.o
.PHONY : index/PostingList.o

# target to build an object file
index/PostingList.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/index/PostingList.cpp.o
.PHONY : index/PostingList.cpp.o

index/PostingList.i: index/PostingList.cpp.i
.PHONY : index/PostingList.i

# target to preprocess a source file
index/PostingList.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/index/PostingList.cpp.i
.PHONY : index/PostingList.cpp.i

index/PostingList.s: index/PostingList.cpp.s
.PHONY : index/PostingList.s

# target to generate assembly for a file
index/PostingList.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/index/PostingList.cpp.s
.PHONY : index/PostingList.cpp.s

index/main.o: index/main.cpp.o
.PHONY : index/main.o

# target to build an object file
index/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/index/main.cpp.o
.PHONY : index/main.cpp.o

index/main.i: index/main.cpp.i
.PHONY : index/main.i

# target to preprocess a source file
index/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/index/main.cpp.i
.PHONY : index/main.cpp.i

index/main.s: index/main.cpp.s
.PHONY : index/main.s

# target to generate assembly for a file
index/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/search_engine.dir/build.make CMakeFiles/search_engine.dir/index/main.cpp.s
.PHONY : index/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... search_engine"
	@echo "... index/ISR.o"
	@echo "... index/ISR.i"
	@echo "... index/ISR.s"
	@echo "... index/Ipost.o"
	@echo "... index/Ipost.i"
	@echo "... index/Ipost.s"
	@echo "... index/Post.o"
	@echo "... index/Post.i"
	@echo "... index/Post.s"
	@echo "... index/PostingList.o"
	@echo "... index/PostingList.i"
	@echo "... index/PostingList.s"
	@echo "... index/main.o"
	@echo "... index/main.i"
	@echo "... index/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

